services:
  web:
    build: ./mealList
    image: phufarpsw/meallist_frontend:lastest
    ports:
      - "4000:4000"
    container_name: frontend
  server:
    build: ./backend
    image: phufa/meallist_backend:lastest
    ports:
      - "3000:3000"
    container_name: backend
